spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
github:
  api-url: https://api.github.com
  token: ${GITHUB_API_TOKEN}
application:
  import-frequency: ${ISSUES_IMPORT_FREQUENCY:60000}
  challenge-frequency: ${ISSUES_CHALLENGE_FREQUENCY:10000}
  one-signal:
    api-auth-key: ${ONE_SIGNAL_API_AUTH_KEY}
    new-challenge-template-id: "2316b607-fb66-40be-bb20-780048c0e934"
    app-id: ${APP_ID}
